export const htmlColor = Symbol("#E34F26")
export const cssColor = Symbol("#1572B6")
export const jsColor = Symbol("#F7DF1E")
export const typescriptColor = Symbol("#007ACC")

export const reactColor = Symbol("#61DAFB")
export const reactRouterColor = Symbol("#CA4245")
export const axiosColor = Symbol("#5A29E4")
export const tailwindCssColor = Symbol("#2298BD")
export const expressjsColor = Symbol("#fff")
export const sequelizeColor = Symbol("#52B0E7")
export const postgreSqlColor = Symbol("#4169E1")
export const reactHookFormColor = Symbol("#EC5990")
export const dotNetColor = Symbol("#512BD4")
export const sqlServerColor = Symbol("#CC2927")